siteiscte/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('votacao/', include('votacao.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

votacao/urls.py
from django.urls import path
from . import views

app_name = 'votacao'
urlpatterns = [
    # ex: votacao
    path('', views.index, name='index'),
    # ex: votacao/1
    path('<int:questao_id>', views.detalhe, name='detalhe'),
    # ex: votacao/3/resultados
    path('<int:questao_id>/resultados', views.resultados, name='resultados'),
    # ex: votacao/5/voto
    path('<int:questao_id>/voto', views.voto, name='voto'),
    # ex: votacao/criarquestao
    path('criarquestao', views.criarquestao, name='criarquestao'),
    # ex: votacao/criarquestao/inserirquestao
    path('criarquestao/inserirquestao', views.inserirquestao, name='inserirquestao'),
    # ex votacao/2/criaropcao
    path('<int:questao_id>/criaropcao', views.criaropcao, name='criaropcao'),
    # ex votacao/2/criaropcao/inseriropcao
    path('<int:questao_id>/criaropcao/inseriropcao', views.inseriropcao, name='inseriropcao'),

    path('fazlogin', views.fazlogin, name='fazlogin'),
    path('fazlogout', views.fazlogout, name='fazlogout'),

    # ex votacao/registar
    path('registar', views.registar, name='registar'),

    # ex votacao/verperfil
    path('verperfil', views.verperfil, name='verperfil'),

    # ex votacao/1/apagarquestao
    path('<int:questao_id>/apagarquestao', views.apagarquestao, name='apagarquestao'),

    # ex votacao/6/apagaropcao
    path('<int:questao_id>/apagaropcao', views.apagaropcao, name='apagaropcao'),

    # ex votacao/verperfil/upload_profimg
    path('verperfil/upload_profimg', views.upload_profimg, name='upload_profimg')
]

votacao/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Questao:
# texto da questão e data de publicação
class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')


# Opcao:
# texto da opção e número de votos
# chave estrangeira muitos-para-um pois uma Questao pode ter várias instancias de Opcao
class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)


class Aluno(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    curso = models.CharField(max_length=50)
    num_votos = models.IntegerField(default=0)

votacao/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required, user_passes_test

from .models import Questao, Opcao, Aluno
from django.urls import reverse

import os


def test_superuser(user):
    return user.is_superuser


def index(request):
    if 'error_message' in request.session:
        del request.session['error_message']

    if request.user.is_authenticated:
        try:
            aluno = Aluno.objects.get(user=request.user)
            request.session['num_votos'] = aluno.num_votos

        except (KeyError, Aluno.DoesNotExist):
            pass

        pic_list = os.listdir('votacao/static/media/')
        fs = FileSystemStorage()
        for filename in pic_list:
            if filename.startswith(request.user.username + '_'):
                profile_pic_url = fs.url(filename)
                request.session['profile_pic_url'] = profile_pic_url
                break

    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    context = {'latest_question_list': latest_question_list}

    return render(request, 'votacao/index.html', context)


@login_required(login_url='/votacao/fazlogin')
def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao, })


@login_required(login_url='/votacao/fazlogin')
def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/resultados.html', {'questao': questao})


@login_required(login_url='/votacao/fazlogin')
def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_selecionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta novo form para votar
        return render(request, 'votacao/detalhe.html',
                      {'questao': questao,
                       'error_message': "Não escolheu uma opção",
                       })
    else:
        try:
            aluno = Aluno.objects.get(user=request.user)
            if aluno.num_votos < 19:
                aluno.num_votos += 1
                aluno.save()
            else:
                request.session['error_message'] = 'O Aluno atingiu o número de votos permitido'
                return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao_id,)))
        except (KeyError, Aluno.DoesNotExist):
            pass

        opcao_selecionada.votos += 1
        opcao_selecionada.save()

    return HttpResponseRedirect(reverse('votacao:resultados', args=(questao_id,)))


@user_passes_test(test_superuser, login_url='/votacao/')
def criarquestao(request):
    return render(request, 'votacao/criarquestao.html')


@user_passes_test(test_superuser, login_url='/votacao/')
def inserirquestao(request):
    questao_texto = request.POST['questaotexto']
    print(questao_texto)
    if questao_texto:
        questao = Questao(questao_texto=questao_texto, pub_data=timezone.now())
        questao.save()
        return HttpResponseRedirect(reverse('votacao:index'))
    else:
        return render(request, 'votacao/criarquestao.html', {'error_message': "Introduza o texto da questão!"})


@user_passes_test(test_superuser, login_url='/votacao/')
def criaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/criaropcao.html', {'questao': questao})


@user_passes_test(test_superuser, login_url='/votacao/')
def inseriropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    opcaotexto = request.POST['opcaotexto']
    if opcaotexto:
        questao.opcao_set.create(questao=questao, opcao_texto=opcaotexto)
        return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao_id,)))
    else:
        return render(request, 'votacao/criaropcao.html',
                      {'questao': questao, 'error_message': "Introduza o texto da opcão!"})


def fazlogin(request):
    if request.method == 'POST':
        # tratar os dados do form de login, neste caso username e password
        name = request.POST['username']
        passwd = request.POST['password']

        u = authenticate(username=name, password=passwd)
        if u is not None:
            login(request, u)
            return HttpResponseRedirect(reverse('votacao:index'))

        else:
            # return do formulário de login
            return render(request, 'votacao/login.html', {'msg_erro': 'Credenciais inválidas!'})
    else:
        return render(request, 'votacao/login.html')


@login_required(login_url='/votacao/fazlogin')
def fazlogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('votacao:index'))


def registar(request):
    if request.method == 'POST':
        name = request.POST['username']
        email = request.POST['email']
        passwd = request.POST['password']
        curso = request.POST['curso']

        u = User.objects.create_user(username=name, email=email, password=passwd)
        Aluno.objects.create(user=u, curso=curso)
        return HttpResponseRedirect(reverse('votacao:fazlogin'))
    return render(request, 'votacao/registar.html')


@login_required(login_url='/votacao/fazlogin')
def verperfil(request):
    return render(request, 'votacao/verperfil.html',)


@user_passes_test(test_superuser, login_url='/votacao/')
def apagarquestao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    questao.delete()
    return HttpResponseRedirect(reverse('votacao:index'))


@user_passes_test(test_superuser, login_url='/votacao/')
def apagaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_selecionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'votacao/detalhe.html',
                      {'questao': questao,
                       'error_message': "Não escolheu uma opção",
                       })
    else:
        opcao_selecionada.delete()
        return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao_id,)))


@login_required(login_url='/votacao/fazlogin')
def upload_profimg(request):
    if request.method == 'POST' and 'myfile' in request.FILES:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        pic_list = os.listdir('votacao/static/media/')
        for fn in pic_list:
            if fn.startswith(request.user.username + '_'):
                os.remove('votacao/static/media/' + fn)
                break

        filename = fs.save(request.user.username + '_' + myfile.name, myfile)
        profile_pic_url = fs.url(filename)
        request.session['profile_pic_url'] = profile_pic_url
        return HttpResponseRedirect(reverse('votacao:verperfil'))
    return HttpResponseRedirect(reverse('votacao:verperfil'))

votacao/templates/votacao/criaropcao.html
{% extends './index.html' %}

{% block titulo %}
    Criar opção
{% endblock %}

<body>

{% block conteudoprincipal %}


    <div class="login-container">
    <h1 class="login-title"><label for="opcaotexto"> Criar Opção para a Questão "{{ questao.questao_texto }}"</label></h1>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form method="POST" action="{% url 'votacao:inseriropcao' questao.id %}" >
            {% csrf_token %}
            <input class="login-input" type="text" name="opcaotexto"
                   placeholder="Introduza o texto da nova opção">
            <br>
            <input class="submit" type="submit" value="Submeter">
        </form>
    </div>
    
{% endblock %}

</body>
</html>

votacao/templates/votacao/criarquestao.html
{% extends './index.html' %}

{% block titulo %}
    Criar questão
{% endblock %}

<body>
{% block conteudoprincipal %}
    <div class="login-container">
        <h1 class="login-title"><label for="questaotexto">Nova Questão:</label></h1>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form method="POST" action="{% url 'votacao:inserirquestao' %}">
            {% csrf_token %}
            <input class="login-input" type="text" name="questaotexto"
                   placeholder="Introduza o texto da nova questão">
            <br>
            <input class="submit" type="submit" value="Submeter">
        </form>
    </div>
{% endblock %}
</body>
</html>

votacao/templates/votacao/detalhe.html
{% extends './index.html' %}

{% block titulo %}
    Esta é a página da questão nº {{ questao.id }}
{% endblock %}


<body>

{% block conteudoprincipal %}
    <div class="login-container">
        <h1>Questão: {{ questao.questao_texto }}</h1>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        {% if request.session.error_message %}
            <strong>{{ request.session.error_message }}</strong>
        {% endif %}

        {% if request.user.is_superuser %}
            <form action="{% url 'votacao:apagarquestao' questao.id %}">
                 <input class="submit" type="submit" formaction="{% url 'votacao:apagarquestao' questao.id %}" value="Apagar Questão">
            </form>
        {% endif %}

        <br>

        {% if questao.opcao_set %}
            <form action="{% url 'votacao:voto' questao.id %}"
                  method="post">
                {% csrf_token %}
                <div class="radio-container">
                    {% for opcao in questao.opcao_set.all %}
                        <input type="radio" name="opcao"
                               id="opcao{{ forloop.counter }}"
                               value="{{ opcao.id }}" />
                        <label for="opcao{{ forloop.counter }}">
                            {{ opcao.opcao_texto }}
                        </label>
                        <br>
                        <div id="num-votos{{ forloop.counter }}" style="display: none">
                            <div class="login-input">
                                Total de votos desta opção: {{ opcao.votos }}
                            </div>
                        </div>
                    {% endfor %}
                </div>

                {% if request.user.is_authenticated %}
                    <input class="submit" type="submit" value="Voto" />
                {% endif %}

                {% if request.user.is_superuser %}
                    <br>
                    <br>
                    <input class="submit" type="submit" formaction="{% url 'votacao:criaropcao' questao.id %}" value="Criar Opcao"></input>
                    <br>
                    <br>
                    <input class="submit" type="submit" formaction="{% url 'votacao:apagaropcao' questao.id %}" value="Apagar Opcao">
                {% endif %}
            </form>
        {% else %}
            <p>Não há opções disponíveis para esta questão!</p>
            {% if request.user.is_superuser %}
                <form>
                    <input type="submit" formaction="{% url 'votacao:criaropcao' questao.id %}" value="Criar Opcao"></input>
                    <br>
                </form>
            {% endif %}
        {% endif %}
        <br>
    </div>
{% endblock %}

</body>
</html>

votacao/templates/votacao/fazerupload.html
{% extends './index.html' %}

{%  block titulo %}
    Fazer Upload
{% endblock %}

{% block conteudoprincipal %}

    <form action="{% url 'votacao:upload_profimg' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile">
        <input type="submit" value="Carregar ficheiro">

    </form>

{% endblock %}

votacao/templates/votacao/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
            Página de entrada
        {% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'votacao/css/style.css' %}?{% now "U" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{%  static 'votacao/js/scripts.js' %}"></script>
</head>

<body>

<header>
    <div class="container">

        <div style="height: 50px">
            <div id="sessioninfo">
                {% if request.user.is_authenticated %}
                    <h2>O user <span id="user-click-img">{{ request.user.username }}</span> está logado</h2>
                {% else %}
                    <h2>Não está logado...</h2>
                {% endif %}
            </div>


            <div id="header_profileimage">
                {% if request.session.profile_pic_url %}
                    <img style="width: 50px; height: 50px" class="profileimg"
                         src="{{ request.session.profile_pic_url }}" alt="Profile Image">
                {% else %}
                    <img style="width: 50px; height: 50px" class="profileimg" src="../../static/media/default.png">
                {% endif %}
            </div>
        </div>


    </div>
    <div id="banner"></div>
</header>

<div class="container_background">
    <div class="container">
        <nav class="mainnav">
             {% if request.user.is_authenticated %}
                <ul>
                    {% if request.user.aluno %}
                        <li class="main_nav_li"><a href="{% url 'votacao:fazlogout' %}">Logout</a></li>
                        <li class="main_nav_li"><a href="{% url 'votacao:verperfil' %}">Ver perfil</a></li>
                        <li class="main_nav_li"><a href="{% url 'votacao:index' %}">Página inicial</a></li>

                    {% else %}
                        <li class="main_nav_li"><a href="{% url 'votacao:fazlogout' %}">Logout</a></li>
                        {% if request.user.is_superuser %}
                            <li class="main_nav_li"><a href="{% url 'votacao:verperfil' %}">Ver perfil</a></li>
                            <li class="main_nav_li"><a href="{% url 'votacao:criarquestao' %}">Criar Questão</a></li>
                        {% endif %}
                        <li class="main_nav_li"><a href="{% url 'votacao:index' %}">Página inicial</a></li>

                    {% endif %}
                </ul>
             {% else %}
                 <ul>
                    <li class="main_nav_li"><a href="{% url 'votacao:registar' %}">Registar</a></li>
                    <li class="main_nav_li" style="color: white">|</li>
                    <li class="main_nav_li"><a href="{% url 'votacao:fazlogin' %}">Login</a></li>
                    <li class="main_nav_li"><a href="{% url 'votacao:index' %}">Página inicial</a></li>
                 </ul>
             {% endif %}
        </nav>
    </div>
</div>



{% block conteudoprincipal %}
    <div class="container">
    {% if latest_question_list %}
        <div id="question-list">
            <h1 id="questionlisttitle">Lista de perguntas</h1>
            {% for questao in latest_question_list %}
                <div class="box" onclick='location.href="{% url 'votacao:detalhe' questao.id %}"' >
                    {{ questao.questao_texto }}
                </div>
            {% endfor %}
        </div>
        <button  class="upload-submit" id="hide-show-quest" onclick="esconder_mostrar()" value="0">
            Mostrar lista de questões
        </button>

    {% else %}
        <div class="container">
            <p>Não há questoes disponíveis.</p>
        </div>

    {% endif %}

    <div id="slideshow">
        <img src="">
    </div>

    </div>


{% endblock %}

</body>
</html>

votacao/templates/votacao/login.html
{% extends './index.html' %}

{% block titulo %}
    Página de login
{% endblock %}


<body>
{% block conteudoprincipal %}
    <div class="login-container">
        {% if msg_erro %}
            <h2>{{ msg_erro }}</h2>
        {% endif %}

        <h1 class="login-title">Login</h1>
        <form action="{% url 'votacao:fazlogin' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <br>
            <input class="login-input" type="text" name="username" autofocus required>
            <br>
            <label for="password">Password:</label>
            <br>
            <input class="login-input" type="password" name="password" required>
            <br>
            <input class="submit" type="submit" value="Entrar">
        </form>
    </div>
{% endblock %}
</body>
</html>

votacao/templates/votacao/registar.html
{% extends './index.html' %}

{% block titulo %}
    Página de registo
{% endblock %}

<body>
{% block conteudoprincipal %}
    <div class="login-container">
        <h1 class="login-title">Registar</h1>
            <form action="{% url 'votacao:registar' %}" method="POST">
                {% csrf_token %}
                <label for="username">Username:</label>
                <br>
                <input class="login-input" type="text" name="username" autofocus required>
                <br>
                <label for="email">Email:</label>
                <br>
                <input class="login-input" type="email" name="email">
                <br>
                <label for="password">Password:</label>
                <br>
                <input class="login-input" type="password" name="password" required>
                <br>
                <label for="curso">Curso</label>
                <br>
                <input class="login-input" type="text" name="curso" required>
                <br>
                <label for="comment">Insira um comentário:</label>
                <br>
                <input class="login-input" id="comment" type="text" name="comment">
                <div class="login-input" id="comment-result"></div>
                <button type="button" class="upload-submit" id="validate" onclick="validateComment()">Validar comentário</button>
                <br>
                <input class="submit" type="submit" value="Registar">
            </form>
    </div>
{% endblock %}
</body>
</html>

votacao/templates/votacao/resultados.html
{% extends './index.html' %}

{% block titulo %}
    Resultados da questão nº {{ questao.id }}
{% endblock %}

<body>
{% block conteudoprincipal %}

    <div class="login-container">
        <h1>Questão: {{ questao.questao_texto }}</h1>
        <ul>
            {% for opcao in questao.opcao_set.all %}
                <li>{{ opcao.opcao_texto }} -- {{ opcao.votos }}
                    voto{{ opcao.votos|pluralize }}</li>
            {% endfor %}
        </ul>
        <br>
        <form>
            <input class="submit" type="submit" formaction="{% url 'votacao:detalhe' questao.id %}"
                   value="Votar Novamente">
        </form>
        </div>
{% endblock %}
</body>
</html>

votacao/templates/votacao/verperfil.html
{% extends './index.html' %}

{% block titulo %}
    Perfil do {{ request.user.username }}
{% endblock %}


<body>
{% block conteudoprincipal %}

    <div id="showprofile">

        {% if request.session.profile_pic_url %}
            <img class="profileimg" src="{{ request.session.profile_pic_url }}" alt="Profile Image">
        {% else %}
            <img class="profileimg" src="../../static/media/default.png">
        {% endif %}
        <div class="upload-container">
            <form action="{% url 'votacao:upload_profimg' %}"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" class="upload-input" accept="image/*" name="myfile">
                <input type="submit" class="upload-submit" value="Upload">
            </form>
        </div>
        <div id="user-info">
            <h1 id="username">{{ request.user.username }}</h1>
            <p class="profileinfo">Email: {{ request.user.email }}</p>
            {% if not request.user.is_superuser %}
                <p class="profileinfo">Curso: {{ request.user.aluno.curso }}</p>
                <p class="profileinfo">Número de votos: {{ request.user.aluno.num_votos }}</p>
            {% else %}
                <p class="profileinfo">Perfil de Superuser</p>
            {% endif %}
        </div>

    </div>


{% endblock %}
</body>
</html>